FROM node:18-alpine

WORKDIR /app

COPY frontend/package.json frontend/yarn.lock ./

RUN yarn install

COPY frontend/ ./

ENV REACT_APP_BACKEND_URL=http://localhost:8001

EXPOSE 3000

CMD ["yarn", "start"]